#!/usr/bin/env php
<?php
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}
$app = new Symfony\Component\Console\Application('Magic Command', '1.0.0');
$app->add(new CommandeMagique\Installer\Console\InstallerCommand);
$app->run();